[package]
name = "execute"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.17"
crossbeam-queue = "0.3"
wait-timeout = "0.2"

[dev-dependencies]
criterion = "0.5"
tokio = { version = "1.40", features = ["process", "time", "rt-multi-thread"] }